/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DTraceProbe {
  fire(): void
}

export declare class DTraceProvider {
  addProbe(name: string, types: Array<string>): DTraceProbe
  enable(): void
  disable(): void
  fire(probeName: string): void
}

export declare function createDtraceProvider(name: string, module?: string | undefined | null): DTraceProvider
