/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DTraceProbe {
  fire(): void
  fire_with_args(args: Array<string>): void
}

export declare class DTraceProvider {
  addProbe(name: string, types: Array<string>): DTraceProbe
  enable(): void
  disable(): void
  fire(probeName: string): void
  fire_with_args(probeName: string, args: Array<string>): void
}

export declare function createDtraceProvider(name: string, module?: string | undefined | null): DTraceProvider
